### ISSUE TITLE
Kaya ba i-detect type of user gamit Microsoft account?

### ISSUE THREAD

**Issue by jhaimec** [jhaimecando27/CRS-Grad#11]
Kaya ba i-detect type of user gamit Microsoft account? Parang mag cr-create account lang based sa ibabato ng API ng Microsoft. Tas parang hindi madedetect dun (check screenshot for list of data na ibabata ng API). Merong `jobTitle` na key, wala nmn laman.

**Screenshots**
![Screenshot from 2023-11-11 12-41-25](https://github.com/jhaimecando27/CRS-Grad/assets/74945153/d08e5953-c343-467f-af4e-f32e923d50b9)

**Comment by james-martinez0** [comment]
Hindi pre. Ang balak ko dyan yung email lang kukunin dyan tapos ichecheck sa database kung nageexist tapos ilologin. yung type ng user yung middleware na nh laravel bahala base dun sa email.

**Comment by james-martinez0** [comment]
Ayusin ko tong login today. Minadali ko lang kasi yan para may ma-present tayo.

**Comment by jhaimec** [comment]
> yung email lang kukunin dyan tapos ichecheck sa database kung nageexist tapos ilologin. 

okay sige ganyan nlng

**Comment by jhaimec** [comment]
Okay, may na discover ako hahahaha. 

**Hindi to option, Parang reason kung bakit need ng database ng PLM hindi yung sa Microsoft**

Sa [Entra Microsoft](https://entra.microsoft.com/) (which is yung ginamit para sa Microsoft Graph) makikita lahat ng member ng organization which is yung lahat ng members ng PLM basta may plm email sila, and pede makuha lahat ng information na yun hahaha eto tas naka csv na sya:

Eto yung sa website [Entra Microsoft](https://entra.microsoft.com/) (**Identity -> Users -> All Users**)
![image](https://github.com/jhaimecando27/CRS-Grad/assets/74945153/af688140-a011-45ca-b816-4414d7f1e19f)

**Eto yung csv file**:

![image](https://github.com/jhaimecando27/CRS-Grad/assets/74945153/6100ccc0-873f-49ef-bfd2-aa131a8c89bd)

**So what?**

So possible siguro ma-access mga data na to sa API ng Microsoft. Pero, kulang kulang data nila hahaha. Useful sana knowing na may `jobTitle` tas `department`. Pero kulang kulang tas walang standardization like iba iba yung naming. Eto yung mga nakita ko:
- Sa `department`: 'CET - BSCS-CS', 'CET-BS ECE', 'CET' (Iba iba yung naming)
- Sa `jobTitle`: 'Student', 'STUDENT', 'CBGM - BSBA MM', 'CS Faculty' (iba iba naming & mostly blank)

And may mga info na meron sa existing system na wala sa Microsoft. So better kung may existing database tlga.

**Comment by james-martinez0** [comment]
Ang naisip kong proper process dyan is kapag gumawa ng account sa crs dapat naka automate din syang gagawa ng microsoft account na gamit yung same data para consistent.

**Comment by jhaimec** [comment]
Pede ganun. May [doc](https://learn.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http) yung microsoft dun. Pero yung mangyayari ee mag papalit tayo ng package. Yung package kasi na ginagamit natin na naka Microsoft Graph na, ee parang wala pang feature na ganun. Bali mangyayari ee from the scratch natin gagawin yung Microsoft Graph which ginawa na ng current package natin.

eto yung [sample](https://github.com/microsoftgraph/msgraph-sample-phpapp/tree/main/graph-tutorial) ng microsoft, gamit nila laravel. In case lng pag mag manual tayo.

eto nmn yung [doc](https://docs.dcblog.dev/docs/laravel-microsoft-graph/v3/introduction) ng package ng ginagamit natin.
