### ISSUE TITLE
(faculty): error on login

### ISSUE THREAD

**Issue by jhaimec** [jhaimecando27/CRS-Grad#52]
**Describe the bug**
error on login in faculty module

**Screenshots**
![image](https://github.com/jhaimecando27/CRS-Grad/assets/74945153/6bb31891-09c6-4a94-81fd-ee072e1fbbb0)

**Comment by jhaimec** [comment]
@james-zenitram pano nag occur to? trinay ko sa fresh install gamit yung master branch wala nmn naging problem regarding sa `employee_id`. yung naging problem na encounter ko is yung sa editing part lng.

**Comment by james-martinez0** [comment]
nung inimport ko yung laman ng database ni Tom gumana. Kulang kasi laman ng database ko kasi may problem sa seeder

**Comment by jhaimec** [comment]
so hindi na yun problem?
