### ISSUE TITLE
To much permission in OAuth

### ISSUE THREAD

**Issue by jhaimec** [jhaimecando27/CRS-Grad#8]
Masyado madami nakalagay sa permissions. User data lng nmn kailangan siguro.

**To Reproduce**

- Connect to PLM Outlook

**Screenshot**
![Screenshot from 2023-11-11 12-18-12](https://github.com/jhaimecando27/CRS-Grad/assets/74945153/316147d0-0788-4fdc-aab8-b736f1febbfd)

**Comment by james-martinez0** [comment]
Isang permission lang nilagay ko, di ko alam kung bakit ang dami dyan.

![image](https://github.com/jhaimecando27/CRS-Grad/assets/42081063/1126eafb-9165-4c5f-937d-0081538d28ed)

**Comment by jhaimec** [comment]
https://github.com/jhaimecando27/CRS-Grad/blob/fbbca3806ce8516ab68bab0645394f8cd0b6cba0/config/msgraph.php#L58

eto ata salarin hahaha
