### ISSUE TITLE
Synchronize Miscrosoft ID with database User ID?????

### ISSUE THREAD

**Issue by jhaimec** [jhaimecando27/CRS-Grad#9]
Na alala ko lng na na question samin dati yung haba ng ID sa DB. Parang may something related sa security ata. Sa ID ng microsoft mahaba nmn, kaya better siguro kung yun sundan?

Yung sa screenshot yun yung data kasama yung ID na binabato ng API ng Microsoft satin

**Screenshoot**
![image](https://github.com/jhaimecando27/CRS-Grad/assets/74945153/bbb4bd0b-70ed-458e-be13-bf7c3c5a60db)

**Comment by james-martinez0** [comment]
Para sakin di sya feasible kasi yung system natin yung gagawa ng user. Bali ang magiging process kapag ganyan is gagawa si admin ng user sa crs natin tapos mag-query sya kay microsoft para lang makuha yung ID based sa email or name nung ininput ni admin.

Or kapag hindi pa existing yung account yung system natin ang gagawa ng account sa microsoft which is di natin kaya kasi wala tayong admin account sa microsoft.

**Comment by james-martinez0** [comment]
Kung gusto mo lang is yung mahaba ang id ng user for security at di naman need same sya kay microsoft, pwede naman gawin nalang nating UUID yung imbes na INT lang sya.

**Comment by jhaimec** [comment]
gawin nlng nating UUID

**Comment by james-martinez0** [comment]
sinubukan ko i-implement yung UUID gamit tong tutorial
https://dev.to/adnanbabakan/implement-uuid-primary-key-in-laravel-and-its-benefits-55o3

medyo matrabaho sya at di ko sure kung makakaapekto sya sa development time ng system kasi mag-iiba din yung way ng saving at retrieving. ang alam ko kasi naka default si laravel sa id. 

kaya di ko muna tinapos

**Comment by jhaimec** [comment]
parang simple lng sinabi dito sa [docu ng laravel](https://laravel.com/docs/10.x/eloquent#uuid-and-ulid-keys) hahaha

>  di ko sure kung makakaapekto sya sa development time ng system
- Oo, maapektohan yung dev time

Sige ano nlng. Stick muna nlng siguro sa `id()`. Hindi ko pa nakikita kung mas worth it ba yung UUID unless security yung pinag uusapan. Pag sinabi nlng siguro nila.

**Comment by jhaimec** [comment]
late close
